"use client";

import { PointerEvent, useRef, useState } from "react";
import { useLanguage } from "./LanguageProvider";

type Sticker = { id: number; stickerId: string; x: number; y: number; rotation: number };
type Picker = { x: number; y: number; boardX: number; boardY: number; target?: number } | null;
const library = [
  { id: "quotes", src: "/images/stickers/sticker-quotes.png", label: "Aspas" }, { id: "sparkle", src: "/images/stickers/sticker-sparkle.png", label: "Brilho" }, { id: "pen", src: "/images/stickers/sticker-pen.png", label: "Caneta" }, { id: "appstore", src: "/images/stickers/sticker-appstore.png", label: "App Store" }, { id: "note", src: "/images/stickers/sticker-note.png", label: "Nota" }, { id: "fingerprint", src: "/images/stickers/sticker-fingerprint.png", label: "Digital" },
];
const initial: Sticker[] = [{ id: 1, stickerId: "quotes", x: 11, y: 22, rotation: 15.2 }, { id: 2, stickerId: "sparkle", x: 7, y: 54, rotation: 0 }, { id: 3, stickerId: "pen", x: 18, y: 70, rotation: 180 }, { id: 4, stickerId: "appstore", x: 72, y: 12, rotation: 23.36 }, { id: 5, stickerId: "note", x: 74, y: 46, rotation: -18.03 }, { id: 6, stickerId: "fingerprint", x: 62, y: 75, rotation: -9.83 }];

export function StickerContact() {
  const [stickers, setStickers] = useState(initial); const [picker, setPicker] = useState<Picker>(null); const [info, setInfo] = useState(false); const board = useRef<HTMLDivElement>(null); const drag = useRef<{ id: number; dx: number; dy: number } | null>(null); const id = useRef(7); const { t } = useLanguage();
  const showPicker = (event: React.MouseEvent, target?: number) => { event.preventDefault(); event.stopPropagation(); const box = board.current?.getBoundingClientRect(); if (!box) return; setPicker({ x: event.clientX, y: event.clientY, boardX: event.clientX - box.left, boardY: event.clientY - box.top, target }); };
  const selectSticker = (stickerId: string) => { if (!picker || !board.current) return; if (picker.target) setStickers((items) => items.map((item) => item.id === picker.target ? { ...item, stickerId } : item)); else { const box = board.current.getBoundingClientRect(); setStickers((items) => [...items, { id: id.current++, stickerId, x: Math.max(4, Math.min(92, picker.boardX / box.width * 100)), y: Math.max(5, Math.min(85, picker.boardY / box.height * 100)), rotation: Math.random() * 30 - 15 }]); } setPicker(null); };
  const startDrag = (event: PointerEvent<HTMLButtonElement>, sticker: Sticker) => { const box = board.current?.getBoundingClientRect(); if (!box) return; event.currentTarget.setPointerCapture(event.pointerId); drag.current = { id: sticker.id, dx: event.clientX - box.left - box.width * sticker.x / 100, dy: event.clientY - box.top - box.height * sticker.y / 100 }; };
  const move = (event: PointerEvent<HTMLDivElement>) => { if (!drag.current || !board.current) return; const box = board.current.getBoundingClientRect(); const x = (event.clientX - box.left - drag.current.dx) / box.width * 100; const y = (event.clientY - box.top - drag.current.dy) / box.height * 100; setStickers((items) => items.map((item) => item.id === drag.current?.id ? { ...item, x: Math.max(3, Math.min(92, x)), y: Math.max(3, Math.min(88, y)) } : item)); };
  return <section className="contact shell" id="contato"><div ref={board} className="contact-box" onContextMenu={showPicker} onPointerMove={move} onPointerUp={() => { drag.current = null; }} onClick={() => setPicker(null)}>{stickers.map((sticker) => { const asset = library.find((item) => item.id === sticker.stickerId)!; return <button key={sticker.id} className="sticker" style={{ left: `${sticker.x}%`, top: `${sticker.y}%`, transform: `translate(-50%, -50%) rotate(${sticker.rotation}deg)` }} aria-label={asset.label} onPointerDown={(event) => startDrag(event, sticker)} onContextMenu={(event) => showPicker(event, sticker.id)}><img src={asset.src} alt="" /></button>; })}<div className="contact-info" onMouseEnter={() => setInfo(true)} onMouseLeave={() => setInfo(false)}>{info && <span>{t.contact.hint}</span>}<b>i</b></div><div className="contact-content"><h2>{t.contact.title}</h2><a className="button dark" href="mailto:juan.developer@icloud.com">{t.contact.cta}</a></div></div>{picker && <div className="sticker-picker" style={{ left: picker.x, top: picker.y }}>{library.map((asset, index) => { const angle = index / library.length * Math.PI * 2 - Math.PI / 2; return <button key={asset.id} title={asset.label} style={{ left: Math.cos(angle) * 72 - 26, top: Math.sin(angle) * 72 - 26 }} onClick={() => selectSticker(asset.id)}><img src={asset.src} alt={asset.label} /></button>; })}<span>{picker.target ? "✦" : "+"}</span></div>}</section>;
}
